version: '3.7'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: lebranc_hongjot
    ports:
      - "5432:5432"
